# This file is machine-generated - editing it directly is not advised

[[BlochSim]]
deps = ["LinearAlgebra"]
git-tree-sha1 = "99727511b81d86625a22f4ac7bccd1458ee17e20"
uuid = "5c0f8cbe-99a4-11e9-108b-216da9629524"
version = "0.3.0"

[[Libdl]]
uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[[LinearAlgebra]]
deps = ["Libdl"]
uuid = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
