name = "STFR"
uuid = "e905d6ce-5d58-11e9-2213-8b5d9f240645"
authors = ["Steven Whitaker <stwhit@umich.edu>"]
version = "1.1.0"

[deps]
BlochSim = "5c0f8cbe-99a4-11e9-108b-216da9629524"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1.2"
BlochSim = "0.2, 0.3"
